import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { css } from 'styled-components'
import { Container } from '@/components/Container'
import { CloseBtn } from '@/components/Button'
import Link from 'next/link'
import { useEffect } from 'react'
import auth, { c_user } from './api/auth'
import { dongle,heyComic } from '@/components/Font'
import texture1 from '../public/Img/bg_texture1.png'


const style = css`
    h2{
        width: 100%;
        justify-content: center;
        display: flex;
        font-size: 3em;
        text-shadow: .75px .75px 0 #000,
        -.75px .75px 0 #000,
        .75px -.75px 0 #000,
        -.75px -.75px 0 #000,
        0px .75px 0 #000,
        0px -.75px 0 #000,
        -.75px 0px 0 #000,
        .75px 0px 0 #000,
        1.25px 1.25px 0 #000,
        -1.25px 1.25px 0 #000,
        1.25px -1.25px 0 #000,
        -1.25px -1.25px 0 #000,
        0px 1.25px 0 #000,
        0px -1.25px 0 #000,
        -1.25px 0px 0 #000,
        1.25px 0px 0 #000,
        .75px 1.25px 0 #000,
        -.75px 1.25px 0 #000,
        .75px -1.25px 0 #000,
        -.75px -1.25px 0 #000,
        1.25px .75px 0 #000,
        -1.25px .75px 0 #000,
        1.25px -.75px 0 #000,
        -1.25px -.75px 0 #000;
    }
    .row h3 {
        font-size: 2em;
        color: black;
    }
`
export default function Leaderboard() {
  useEffect(()=>{
    console.log(c_user)
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>{ style }</style>
      </Head>
      <main className={styles.main} style={{
      backgroundImage: `url(${texture1.src})`,
      height: '100vh',
      backgroundRepeat: 'no-repeat',
    backgroundSize: 'cover',
    }}>
        <Container width="100%" bdradius="0%" color="transparent"  overflowy="scroll">
          <Container width="80%" bdradius="20px" color="#ECD352" border="4px solid #000000" shadow="0px .75px 1.25px rgba(0, 0, 0, 0.1), 0px .75px 1.25px rgba(0, 0, 0, 0.06)" className={dongle.className}>
            <h2 className={heyComic.className}>Leaderboard</h2>
            <Link href='/home'><CloseBtn className={dongle.className} right="-.5em">x</CloseBtn></Link>
            <Container width="90%" height="100%" bdradius="30px" color="white" className={dongle.className}>
                <Container className="row" width="95%" color="transparent">
                    <Container width="60%" color="transparent" padding="0">
                        <h3>Name</h3>
                    </Container>
                    <Container width="20%" color="transparent" padding="0">
                        <h3>Rank</h3>
                    </Container>
                    <Container width="20%" color="transparent" padding="0">
                        <h3>Point</h3>
                    </Container>
                </Container>

                <Container className="row" width="95%" color="rgba(255, 104, 57, 0.84)" shadow="0px 4px 4px rgba(0, 0, 0, 0.25)" bdradius="30px">
                    <Container width="60%" color="transparent" justify="start">
                        <Container width="4em" height="4em" color="white" bdradius="50%" border="2px solid #000000" padding="0"></Container>
                    </Container>
                    <Container width="20%" color="transparent" bdleft="5px solid #E06667" bdradius="0px">
                    </Container>
                    <Container width="20%" color="transparent" bdleft="5px solid #E06667" bdradius="0px" >
                    </Container>
                </Container>

                <Container className="row" width="95%" color="rgba(236, 119, 82, 0.74)" shadow="0px 4px 4px rgba(0, 0, 0, 0.25)" bdradius="30px" mgtop="2em">
                    <Container width="60%" color="transparent" justify="start">
                        <Container width="4em" height="4em" color="white" bdradius="50%" border="2px solid #000000" padding="0"></Container>
                    </Container>
                    <Container width="20%" color="transparent" bdleft="5px solid #E06667" bdradius="0px">
                    </Container>
                    <Container width="20%" color="transparent" bdleft="5px solid #E06667" bdradius="0px" >
                    </Container>
                </Container>

                <Container className="row" width="95%" color="rgba(236, 165, 82, 0.74)" shadow="0px 4px 4px rgba(0, 0, 0, 0.25)" bdradius="30px" mgtop="2em">
                    <Container width="60%" color="transparent" justify="start">
                        <Container width="4em" height="4em" color="white" bdradius="50%" border="2px solid #000000" padding="0"></Container>
                    </Container>
                    <Container width="20%" color="transparent" bdleft="5px solid #E06667" bdradius="0px">
                    </Container>
                    <Container width="20%" color="transparent" bdleft="5px solid #E06667" bdradius="0px" >
                    </Container>
                </Container>

                <Container className="row" width="95%" color="rgba(236, 184, 82, 0.74)" shadow="0px 4px 4px rgba(0, 0, 0, 0.25)" bdradius="30px" mgtop="2em">
                    <Container width="60%" color="transparent" justify="start">
                        <Container width="4em" height="4em" color="white" bdradius="50%" border="2px solid #000000" padding="0"></Container>
                    </Container>
                    <Container width="20%" color="transparent" bdleft="5px solid #E06667" bdradius="0px">
                    </Container>
                    <Container width="20%" color="transparent" bdleft="5px solid #E06667" bdradius="0px" >
                    </Container>
                </Container>

                

                
            </Container>
          </Container>
        </Container>
        

        
      </main>
    </>
  )
}
