import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { css } from 'styled-components'
import { Container } from '@/components/Container'
import Link from 'next/link'
import { useEffect } from 'react'
import auth, { c_user } from './api/auth'
import { dongle,heyComic } from '@/components/Font'
import texture2 from '../public/Img/bg_texture2.png'
import { PictureFlex } from '@/components/Image'
import { Flex, Text, Img, Button, Box } from '@chakra-ui/react'

const style = css`
    
`
export default function Friends() {
  useEffect(()=>{
    console.log(c_user)
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>{ style }</style>
      </Head>
      <Flex bgColor="#FF6839" bgImage="/Img/bg_texture2.png" bgRepeat="no-repeat" bgSize="cover" w="full" h="100vh" justify="center" align="flex-end">

      </Flex>
      <Flex >

      </Flex>
    </>
  )
}
