import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { css } from 'styled-components'
import { Container } from '@/components/Container'
import { Button } from '@/components/Button'
import { useState } from 'react'
import { useRouter } from 'next/router'
import { doc, collection, getFirestore, getDoc } from 'firebase/firestore'
import { firebaseConfig } from '../firebaseSetup'
import { initializeApp } from 'firebase/app'
const style = css`
  ul{
    list-style-type: none;
    justify-content: center;
    align-items: center;
    width: fit-content;
    margin: auto;
  }
  li {
    display: inline-flex;
    margin-left: 1em;
    margin-right: 1em;
  }
`

export default function Home() {
    const router = useRouter();
    const { user } = router.query;
    const username = user.split("_");

    const reInitialize = initializeApp(firebaseConfig);
    const db = getFirestore(reInitialize);

    // async function fetchUserData () {
    //   const data = await getDoc(doc(collection(db, "users"), userID));
    //   return data
    // };
    // const userData = fetchUserData();
  
  
  
//   const doc = getDoc(collection(db, "users"), userID);
//   console.log(doc)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>{ style }</style>
      </Head>
      <main className={styles.main}>
        <Container width="80%">
          <h1>{ username[1] }</h1>
        </Container>
      </main>
    </>
  )
}
